### ISSUE TITLE
Connection can be recycled by different green-lets 

### ISSUE THREAD

**Issue by seenureddy** [zhangi/django_db_pooling#2]
Running with the Django2.2.6, Oracle db7.13, Gunicorn19.9.0, gevent causing this issue. 

`Traceback (most recent call last):                                                                                                                                            File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/base_async.py", line 56, in handle                                                                              self.handle_request(listener_name, req, client, addr)                                                                                                                     File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/ggevent.py", line 160, in handle_request                                                                        addr)                                                                                                                                                                     File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/base_async.py", line 107, in handle_request                                                                     respiter = self.wsgi(environ, resp.start_response)                                                                                                                        File "/usr/local/lib/python3.6/dist-packages/django/core/handlers/wsgi.py", line 139, in __call__                                                                             signals.request_started.send(sender=self.__class__, environ=environ)                                                                                                      File "/usr/local/lib/python3.6/dist-packages/django/dispatch/dispatcher.py", line 175, in send                                                                                for receiver in self._live_receivers(sender)                                                                                                                              File "/usr/local/lib/python3.6/dist-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>                                                                          for receiver in self._live_receivers(sender)                                                                                                                              File "/usr/local/lib/python3.6/dist-packages/django/db/__init__.py", line 46, in reset_queries                                                                                for conn in connections.all():                                                                                                                                            File "/usr/local/lib/python3.6/dist-packages/django/db/utils.py", line 216, in all                                                                                            return [self[alias] for alias in self]                                                                                                                                    File "/usr/local/lib/python3.6/dist-packages/django/db/utils.py", line 216, in <listcomp>                                                                                     return [self[alias] for alias in self]                                                                                                                                    File "/usr/local/lib/python3.6/dist-packages/django_db_pooling/pooling.py", line 88, in _new_get_item                                                                         conn = self.connection_pool[alias].acquire()                                                                                                                              File "/usr/local/lib/python3.6/dist-packages/django_db_pooling/pooling.py", line 64, in acquire                                                                               conn.allow_thread_sharing = True  # connection can be recycled by different green-lets                                                                                  AttributeError: can't set attribute   `

**Comment by simon435500** [comment]
This issue only occurs with Django 2.2+.
Django change [database connection sharing logic](https://github.com/django/django/commit/76990cbbda5d93fda560c8a5ab019860f7efaab7).
The attribute `allow_thread_sharing` become a property.
It can easily be fixed by modifying [this line](https://github.com/zhangi/django_db_pooling/blob/95925d6fd16ec89072a2cd535c6e2bdca3dd8557/django_db_pooling/pooling.py#L64) to `conn.inc_thread_sharing()` when Django version > 2.2
